# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6bed5974a8e8bc7f3a403620be4a6fc4b5cd968528938c9a8b243c14900aeda2c96bfd9a88e66e2efd00474520baf382f5f1125009bcc61c21ea09568537ee5

test:
  secret_key_base: c01bbae557eab71436abcb61175bb50fa2fb74e721df6d4049fb64d0dc1ac7f96005206b40687bcfbfbab724c56c784d4719e9dbf3f6c332ba661097237b48bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
