# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a4a43bed8e5f667ad7693dd096d0a873aec7ec11062c28c5a5420a8afd6fa4b448437f43a3fb5b5266b4a0f6c445082447a255e841ef851154de7b61060c10b

test:
  secret_key_base: 437454d09f9db2c4a0448a4054f854376930fb0a4186a71bff02fdccc1de8819d7cbba22b093d0314592f48e41ed9090760f1f72c546846b8a53897f590a60e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
